-- 001: durable event cursor and pgvector memory fields
-- Run against an existing production database after enabling the vector extension.
CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE audit_events
  ADD COLUMN IF NOT EXISTS sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS uq_audit_events_sequence
  ON audit_events(sequence);

CREATE INDEX IF NOT EXISTS ix_audit_events_run_sequence
  ON audit_events(tenant_id, run_id, sequence);

ALTER TABLE memory_records
  ADD COLUMN IF NOT EXISTS embedding vector(1536),
  ADD COLUMN IF NOT EXISTS embedding_model VARCHAR(128),
  ADD COLUMN IF NOT EXISTS provenance_hash VARCHAR(64);

CREATE INDEX IF NOT EXISTS ix_memory_records_provenance_hash
  ON memory_records(provenance_hash);

CREATE INDEX IF NOT EXISTS ix_memory_records_tenant_kind_created
  ON memory_records(tenant_id, kind, created_at);

-- HNSW is preferred for production approximate nearest-neighbor search.
CREATE INDEX IF NOT EXISTS ix_memory_records_embedding_hnsw
  ON memory_records USING hnsw (embedding vector_cosine_ops);
